
FROM eclipse-temurin:17-jre
RUN useradd -m -s /bin/bash appuser
WORKDIR /app
RUN chown -R appuser:appuser /app
COPY . .
RUN chmod 777 run-with-add-opens.sh
USER appuser
EXPOSE 8081
ENTRYPOINT [ "./run-with-add-opens.sh" ]