pipeline {

    agent any

    parameters {
        choice(name: 'terraformAction', choices: ['apply', 'destroy'], description: 'Choose your terraform action')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        SNYK_TOKEN            = credentials('SNYK_TOKEN')
    }

    stages {

        stage('Checkout') {
            steps {
                dir("eks") {
                    git url: 'https://github.com/amithachar/devsecops-calculator-app.git',
                        branch: 'IAC-scan'
                }
            }
        }

        stage('Snyk Security Scan') {
            steps {
                dir('eks') {
                    sh './iac-code-scan.sh'
                }
            }
        }

        stage('Plan') {
            steps {
                dir('eks') {
                    sh '''
                        terraform init
                        terraform plan -out tfplan
                        terraform show -no-color tfplan > tfplan.txt
                    '''
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'terraform/eks/tfplan.txt'
                    input message: "Do you want to proceed?",
                        parameters: [text(name: 'Plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy') {
            when {
                expression {
                    params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
            steps {
                dir('terraform/eks') {
                    script {
                        if (params.terraformAction == 'apply') {
                            sh 'terraform apply -input=false tfplan'
                        } else {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }

        stage('Backup-Stage') {
            steps {
                dir('terraform/eks') {
                    sh '''
                        aws s3 cp terraform.tfstate \
                        s3://itkannadogaru-terraform-statefile-backup/Chat-bot/dev-eks/
                    '''
                }
            }
        }
    }
}
